---
deployment:
  tasks:
    - /opt/cpanel/ea-nodejs20/bin/npm install
    - /opt/cpanel/ea-nodejs20/bin/npm run build
    - rm -rf /home/laskinaestheticsct/public_html/*
    - cp -R dist/. /home/laskinaestheticsct/public_html/
    - cd server && /opt/cpanel/ea-nodejs20/bin/npm install
